### ISSUE TITLE
Release 0.6.2

### ISSUE THREAD

**Issue by perre78** [GrinPlusPlus/GrinPlusPlus#73]
Since release 0.6.2 about 80% of my grin is not showing up in the wallet. I noticed that the enhanced database is now default, could this have something to do with it? I have not tried to restore the wallet yet.

**Comment by DavidBurkett** [comment]
Hmm, someone else is reporting a similar problem, but I haven't been able to reproduce the issue. I'll look into it some more. Maybe downgrade to 0.6.1 and turn enhanced database off, restart Grin++ and then login. That should give you access to your old grins while I investigate.

**Comment by DavidBurkett** [comment]
@perre78 Actually, I just reproduced it. I figured out roughly what's going on. To fix it: Go to settings and choose check for outputs, and wait 15 settings. See if they're there. You may have to try it one or two times. What's happening is I implemented an auto refresh that ended up interrupting the restore process. My wallet locking logic must not be fully correct.

**Comment by perre78** [comment]
Hi,
Ok, I’ll try that. I noticed that all the grins missing had been transferred before the hard fork. The grin that still was in the 0.6.2 wallet was transferred today but using 0.6.1.

/Per Melinder

**Comment by perre78** [comment]
I tried the check for outputs, but the problem remains. I will try to roll back to 0.6.1 and restore the wallet since I had to remove the previous installation to be able to install an older version. I'll let you know how it goes...

**Comment by DavidBurkett** [comment]
No, don't restore. Uninstalling doesn't remove the data. Just follow the steps I gave

**Comment by DavidBurkett** [comment]
@perre78 I think I tracked down the real issue, and it's not what I said it was. By any chance did you happen to use your seed in another wallet as well?

**Comment by perre78** [comment]
No, I have only used this one wallet with one user and seed. 

/Per Melinder

**Comment by DavidBurkett** [comment]
@perre78 It turns out Grin++ 0.6.2 is not rewinding pre-hardfork outputs correctly. Anyone having the issue can either wait for 0.6.3 (coming out in ~12 hours), or can follow the following steps:

1. Close Grin++
2. %localappdata%\Programs\GrinPlusPlus\resources\app.asar.unpacked\app\bin 
3. Replace Wallet.dll with the one in dll.zip (see attached)
4. Open Grin++
5. Login
6. Go to settings and click "Check for outputs"


[dll.zip](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3460565/dll.zip)

**Comment by perre78** [comment]
@DavidBurkett The new ddl worked fine. Since i had deleted the entire install (all data) I had to restore the wallet. So I installed 0.6.2, then replaced the ddl, then started Grin++, synced, ADD->Restore Wallet and the correct balance is now there. Thanks!
